<a href="https://colab.research.google.com/github/saisampathkumar/AI-Cybersecurity/blob/master/ICP6/L3_Differential_Privacy_ICP6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Toy Differential Privacy - Simple Database Queries

In the context of Deep Learning, Differential Privacy ensures that the DL algorithms learns only what is is supposed to learn from the data while ignoring what it is not supposed to learn from the data. This is called Differential Privacy (DP). But what is DP?





**Differential Privacy (DP):** 
The main goal is to ensure that statistical analysis techniques does not compromise the privacy of any particular individual in the dataset. 

*  Classical privacy defination: privacy is preserved if after the analysis is done, the analyzer does not know anything about the people in the dataset. (No information leak from the data.)

- The Netflix Prize (anonymized simply! Attacked using the Linkage Attack)
- Anonymization is not enough to protect our privacy

A modern definition by Cynthia Dwork:
DP describes a promise made by the data holder to a data subject that:  "you will not be affected by allowing your data to be used in any study or analysis , no matter what other studies, datasets, or information sources are available".


**DP** is a mathematical definition of privacy. In the simplest setting, consider an algorithm that analyzes a dataset and computes statistics about it (such as the data's mean, variance, median, mode, etc.). Such an algorithm is said to be differentially private if by looking at the output, one cannot tell whether any individual's data was included in the original dataset or not. 




---


In this section we're going to play around with Differential Privacy in the context of a database query. The database is going to be a VERY simple database with only one boolean vector. Each row corresponds to a person. Each value corresponds to whether or not that person has a certain private attribute (such as whether they have a certain disease, or whether they are above/below a certain age). 

We are then going to learn how to know whether a database query over such a small database is differentially private or not - and more importantly - what techniques are at our disposal to ensure various levels of privacy


### First We Create a Simple Database

Step one is to create our database - we're going to do this by initializing a random list of 1s and 0s (which are the entries in our database). Note - the number of entries directly corresponds to the number of people in our database.

In [0]:
import torch

# the number of entries in our database
num_entries = 5000

db = torch.rand(num_entries) > 0.5 # returns a new Boolean tensor with each value > 0.5 set to 1 otherwise set to 0
db

tensor([1, 1, 0,  ..., 1, 0, 0], dtype=torch.uint8)

## Project: Generate Parallel Databases

Key to the definition of differenital privacy is the ability to ask the question "When querying a database, if I removed someone from the database, would the output of the query be any different?". Thus, in order to check this, we must construct what we term "parallel databases" which are simply databases with one entry removed. 

In this first project, I want you to create a list of every parallel database to the one currently contained in the "db" variable. Then, I want you to create a function which both:

- creates the initial database (db)
- creates all parallel databases

In [0]:
import torch

In [0]:
def create_db(entries):
  return torch.rand(entries) > 0.5
db = create_db(5000)
db

tensor([0, 1, 1,  ..., 1, 1, 0], dtype=torch.uint8)

In [0]:
# create a function to create paraller db
def get_parallel_dbs(db):

    parallel_dbs = list()

    for i in range(len(db)):
        pdb = torch.cat((db[0:i], db[i+1:]))
        parallel_dbs.append(pdb)
    #print(f'A databse of size {db.shape} was created')
    return parallel_dbs

pdb = get_parallel_dbs(db)


In [0]:
# a helper function for the future
def get_db_and_parallel(num_entries):
  db = torch.rand(num_entries) > 0.5
  pdb = get_parallel_dbs(db)
  return db, pdb

# Lesson: Towards Evaluating The Differential Privacy of a Function

Intuitively, we want to be able to query our database and evaluate whether or not the result of the query is leaking "private" information. As mentioned previously, this is about evaluating whether the output of a query changes when we remove someone from the database. Specifically, we want to evaluate the *maximum* amount the query changes when someone is removed (maximum over all possible people who could be removed). So, in order to evaluate how much privacy is leaked, we're going to iterate over each person in the database and measure the difference in the output of the query relative to when we query the entire database. 

Just for the sake of argument, let's make our first "database query" a simple sum. Aka, we're going to count the number of 1s in the database.

In [0]:
db,pdbs = get_db_and_parallel(5000)

In [0]:
def query(db):
  return torch.sum(db)

In [0]:
db_result = query(db)
print(db_result)

tensor(2525)


In [0]:
sensitivity = 0  
  # maximum difference between query(db) and each query(pdb)
  # return the value of sensitivity
  # loop on each pdb in the pdbs and calculate its distance
  # find the maximum distance <-- that's your sensitivity
for i in pdbs:
    pdb_result = query(i)
    distance = db_result-pdb_result
    if(distance>sensitivity):
       sensitivity = distance
    
print(sensitivity)    
    

tensor(1)


In [0]:
sensitivity

tensor(1)

# Exercise - Evaluating the Privacy of a Function

In the last section, we measured the difference between each parallel db's query result and the query result for the entire database and then calculated the max value (which was 1). This value is called "sensitivity", and it corresponds to the function we chose for the query. Namely, the "sum" query will always have a sensitivity of exactly 1. However, we can also calculate sensitivity for other functions as well.

First, create a function that will accept (1) a query function and (2) a num_items to generate the db and the pdb: 

**Hint:** def sensitivity(query, num_items)

In [0]:
# define a function to calculate the sensitivity of a query
def sensitivity(query, num_items):
  
  # generate the db and the pdbs
  db,pdbs = get_db_and_parallel(num_items)
  
  # query the db
  db_result = query(db)
  # return the value of sensitivity
  # loop on each pdb in the pdbs and calculate its distance
  # find the maximum distance <-- that's your sensitivity
 
  sensitivity = 0
  for i in pdbs:
      pdb_result = query(i)
      distance = db_result-pdb_result
      if(distance>sensitivity):
         sensitivity = distance
  print(sensitivity) 
  return sensitivity  
  

In [0]:
# recreate the sum query we created earlier
def query(db):
  return torch.sum(db)

In [0]:
# test your sensitivity function with the sum query
sensitivity(query,1000)

tensor(1)


tensor(1)

In [0]:
# create a new query function, which finds the mean rather than the sum
def query(db):
  return torch.sum(db.float())/len(db)


In [0]:
# test your sensitivity function of the Mean query
# how much the output value (query) is using informaiton frmo each of the participating observations
sensitivity(query, 1000)

tensor(0.0005)


tensor(0.0005)

Wow! That sensitivity is WAY lower. Note the intuition here. "Sensitivity" is measuring how sensitive the output of the query is to a person being removed from the database. For a simple sum, this is always 1, but for the mean, removing a person is going to change the result of the query by rougly 1 divided by the size of the database (which is much smaller). Thus, "mean" is a VASTLY less "sensitive" function (query) than SUM.

# Exercise: Calculate L1 Sensitivity For Threshold

In this exercise, you need to calculate the sensitivty for the "threshold" function. 

- First compute the sum over the database (i.e. sum(db)) and return whether that sum is greater than a certain threshold.

- Then, create databases of size 10 and threshold of 5 and calculate the sensitivity of the function. 

- Finally, re-initialize the database 10 times and calculate the sensitivity each time.

In [0]:
# define a function to calculate the sensitivity of a query
def sensitivity(query, num_items,tr):
  
  # generate the db and the pdbs
  db,pdbs = get_db_and_parallel(num_items)
  
  # query the db
  db_result = query(db,tr)
  # return the value of sensitivity
  # loop on each pdb in the pdbs and calculate its distance
  # find the maximum distance <-- that's your sensitivity
 
  sensitivity = 0
  for i in pdbs:
      pdb_result = query(i,tr)
      distance = db_result-pdb_result
      if(distance>sensitivity):
         sensitivity = distance
  print(sensitivity) 
  return sensitivity 

In [0]:
# define a fucntion to query the sum and return wethere the sum is greater or less than a threshold
def query(db,tr):
  total = torch.sum(db.float())
  return (total>tr).float()


In [0]:
# the sensitivity with db of size 10 and threshold of 5
sensitivity(query, 10, 5)

0


0

In [0]:
# repeat for 10 times
sensitivity(query, 10,5)
sensitivity(query, 10,5)
sensitivity(query, 10,5)
sensitivity(query, 10,5)
sensitivity(query, 10,5)
sensitivity(query, 10,5)
sensitivity(query, 10,5)
sensitivity(query, 10,5)
sensitivity(query, 10,5)
sensitivity(query, 10,5)

tensor(1.)
0
0
0
0
0
0
tensor(1.)
0
tensor(1.)


tensor(1.)

# A Basic Differencing Attack

Sadly none of the functions we've looked at so far are differentially private (despite them having varying levels of sensitivity). The most basic type of attack can be done as follows.

Let's say we wanted to figure out a specific person's value in the database. All we would have to do is query for the sum of the entire database and then the sum of the entire database without that person!

# Exercise:  Perform a Differencing Attack on Row 10

In this project, construct a database and then demonstrate how you can use  different queries (sum, threshold, and mean) to explose the value of the person represented by row 10 in the database (note, you'll need to use a database with at least 10 rows)

In [0]:
# Perform a differencing attack using the sum query on row
  db,pdbs = get_db_and_parallel(10)
  db

tensor([1, 1, 1, 1, 1, 0, 1, 0, 1, 1], dtype=torch.uint8)

In [0]:
k = 9
for i in range(len(db)):
        pdb = torch.cat((db[0:k-1], db[k+1:]))
        print(pdb)

tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 1, 1, 0, 1, 0], dtype=torch.uint8)


In [0]:
sum(db) 

tensor(8, dtype=torch.uint8)

In [0]:
sum(pdb)

tensor(6, dtype=torch.uint8)

In [0]:
print(sum(db) - sum(pdb))

tensor(2, dtype=torch.uint8)


In [0]:
# Perform a differencing attack using the mean query on row 10
print((sum(db).float()/len(db)) - (sum(pdb).float()/len(pdb)))

tensor(0.0500)


In [0]:
# Perform a differencing attack using the threshold query on row 10
print((sum(db.float())>49)- (sum(pdb.float())>49))

tensor(0, dtype=torch.uint8)


# Project: Local Differential Privacy

As you can see, the basic sum query is not differentially private at all! In truth, differential privacy always requires a form of randomness added to the query. Let me show you what I mean.

### Randomized Response (Local Differential Privacy)

Let's say I have a group of people I wish to survey about a very taboo behavior which I think they will lie about (say, I want to know if they have ever committed a certain kind of crime). I'm not a policeman, I'm just trying to collect statistics to understand the higher level trend in society. So, how do we do this? One technique is to add randomness to each person's response by giving each person the following instructions (assuming I'm asking a simple yes/no question):

- Flip a coin 2 times.
- If the first coin flip is heads, answer honestly
- If the first coin flip is tails, answer according to the second coin flip (heads for yes, tails for no)!

Thus, each person is now protected with "plausible deniability". If they answer "Yes" to the question "have you committed X crime?", then it might becasue they actually did, or it might be becasue they are answering according to a random coin flip. Each person has a high degree of protection. Furthermore, we can recover the underlying statistics with some accuracy, as the "true statistics" are simply averaged with a 50% probability. Thus, if we collect a bunch of samples and it turns out that 60% of people answer yes, then we know that the TRUE distribution is actually centered around 70%, because 70% averaged wtih 50% (a coin flip) is 60% which is the result we obtained. 

However, it should be noted that, especially when we only have a few samples, the this comes at the cost of accuracy. This tradeoff exists across all of Differential Privacy. The greater the privacy protection (plausible deniability) the less accurate the results. 

Let's implement this local DP for our database before!

In [0]:
def noise(db,augdb):
  for i in range(len(db)):
    ran = torch.rand(1) > 0.5
    if ran[0].item() == 1:
      augdb[i] = db[i].item()
    else:
      ran = torch.rand(1) > 0.5
      if ran[0].item() == 1:
        augdb[i] = 1
      else:
        augdb[i] = 0
  return augdb
  

# ran = torch.rand(1) > 0.5
# ran[0].item()

In [0]:
def mean_db(db):
  total = torch.sum(db.float())
  return torch.div(total,len(db)).float()


In [0]:
db = create_db(10) # try this project here!
print(db)
adb1 = create_db(10)
print(adb1)
adb2 = create_db(10)
print(adb2)

augdb1 = noise(db,adb1)

print(augdb1)


mean_value_db = mean_db(db)
mean_value_adb1 = mean_db(adb1)

print ("Original db value: ",mean_value_db)
print ("aug 1 db value: ",(mean_value_db-0.25)/0.5)

tensor([1, 0, 1, 0, 1, 0, 1, 0, 0, 0], dtype=torch.uint8)
tensor([1, 1, 0, 1, 1, 0, 0, 0, 1, 0], dtype=torch.uint8)
tensor([1, 1, 1, 0, 0, 1, 0, 1, 1, 0], dtype=torch.uint8)
tensor([0, 1, 1, 0, 1, 0, 0, 0, 0, 0], dtype=torch.uint8)
Original db value:  tensor(0.4000)
aug 1 db value:  tensor(0.3000)


In [0]:
db = create_db(100) # try this project here!
adb1 = create_db(100)
adb2 = create_db(100)

augdb1 = noise(db,adb1)
augdb2 = noise(db,adb2)

mean_value_db = mean_db(db)
mean_value_adb1 = mean_db(adb1)
mean_value_adb2 = mean_db(adb2)

print ("Original db value: ",mean_value_db)
print ("aug 1 db value: ",(mean_value_adb1-0.25)/0.5)
print ("aug 2 db value: ",(mean_value_adb2-0.25)/0.5)

Original db value:  tensor(0.5000)
aug 1 db value:  tensor(0.5200)
aug 2 db value:  tensor(0.4400)


In [0]:
db = create_db(1000) # try this project here!
adb1 = create_db(1000)
adb2 = create_db(1000)

augdb1 = noise(db,adb1)
augdb2 = noise(db,adb2)

mean_value_db = mean_db(db)
mean_value_adb1 = mean_db(adb1)
mean_value_adb2 = mean_db(adb2)

print ("Original db value: ",mean_value_db)
print ("aug 1 db value: ",(mean_value_adb1-0.25)/0.5)
print ("aug 2 db value: ",(mean_value_adb2-0.25)/0.5)

Original db value:  tensor(0.5110)
aug 1 db value:  tensor(0.5260)
aug 2 db value:  tensor(0.4960)


In [0]:
db = create_db(10000) # try this project here!
adb1 = create_db(10000)
adb2 = create_db(10000)

augdb1 = noise(db,adb1)
augdb2 = noise(db,adb2)

mean_value_db = mean_db(db)
mean_value_adb1 = mean_db(adb1)
mean_value_adb2 = mean_db(adb2)

print ("Original db value: ",mean_value_db)
print ("aug 1 db value: ",(mean_value_adb1-0.25)/0.5)
print ("aug 2 db value: ",(mean_value_adb2-0.25)/0.5)


Original db value:  tensor(0.5030)
aug 1 db value:  tensor(0.5182)
aug 2 db value:  tensor(0.5112)


In [0]:
db = create_db(1000000) # try this project here!
adb1 = create_db(1000000)
adb2 = create_db(1000000)

augdb1 = noise(db,adb1)
augdb2 = noise(db,adb2)

mean_value_db = mean_db(db)
mean_value_adb1 = mean_db(adb1)
mean_value_adb2 = mean_db(adb2)

print ("Original db value: ",mean_value_db)
print ("aug 1 db value: ",(mean_value_adb1-0.25)/0.5)
print ("aug 2 db value: ",(mean_value_adb2-0.25)/0.5)

Original db value:  tensor(0.4999)
aug 1 db value:  tensor(0.4981)
aug 2 db value:  tensor(0.5001)


# Project: Varying Amounts of Noise

In this project, I want you to augment the randomized response query (the one we just wrote) to allow for varying amounts of randomness to be added. Specifically, I want you to bias the coin flip to be higher or lower and then run the same experiment. 

Note - this one is a bit tricker than you might expect. You need to both adjust the likelihood of the first coin flip AND the de-skewing at the end (where we create the "augmented_result" variable).

In [0]:
# recreate the sum query we created earlier

def query(db):
  return torch.sum(db.float())

In [0]:
def meanquery(db):
  return torch.mean(db.float())

In [0]:
# define a function to calculate the sensitivity of a query
def sensitivity(query, num_items,db,pdbs):
 
  # query the db
  db_result = query(db.float())
  # return the value of sensitivity
  # loop on each pdb in the pdbs and calculate its distance
  # find the maximum distance <-- that's your sensitivity
 
  sensitivity = 0
  for i in pdbs:
      pdb_result = query(i)
      distance = db_result-pdb_result
      if(distance>sensitivity):
         sensitivity = distance

  msensitivity = 0
  for i in pdbs:
      pdb_result = query(i)
      distance = abs(db_result-pdb_result)
      if(distance>msensitivity):
         msensitivity = distance
  return sensitivity,msensitivity



In [0]:
def GDP(db,noise1,noise2):
  r1 = query(db) + noise1.item()
  r2 = meanquery(db) + noise2.item()
  return r1,r2

In [0]:
import numpy as np

def cal(E,db,pdbs):
  S1,S2 = sensitivity(query,1000,db,pdbs)
  
  B1 = S1.item()/E
  noise1 = np.random.laplace(0,B1,1)
  
  B2 = S2.item()/E
  noise2 = np.random.laplace(0,B2,1)
  
  return noise1,noise2
  

In [0]:
# generate the db and the pdbs
db,pdbs = get_db_and_parallel(1000)
  
noise1,noise2 = cal(0.5,db,pdbs)

sm = query(db)

mean = meanquery(db)

res, meanres = GDP(db,noise1,noise2)

print("The original Sum value of the DB:",sm.item())

print("The Sum value after adding noise:",res.item())

print("The original Sum value of the DB:",mean.item())

print("The Sum value after adding noise:",meanres.item())

The original Sum value of the DB: 488.0
The Sum value after adding noise: 486.4425048828125
The original Sum value of the DB: 0.4880000054836273
The Sum value after adding noise: -7.506553649902344


In [0]:
noise1,noise2 = cal(0.05,db,pdbs)

sm = query(db)

mean = meanquery(db)

res, meanres = GDP(db,noise1,noise2)

print("The original Sum value of the DB:",sm.item())

print("The Sum value after adding noise:",res.item())

print("The original Sum value of the DB:",mean.item())

print("The Sum value after adding noise:",meanres.item())

The original Sum value of the DB: 488.0
The Sum value after adding noise: 481.38836669921875
The original Sum value of the DB: 0.4880000054836273
The Sum value after adding noise: -22.28865623474121


In [0]:
noise1,noise2 = cal(0.005,db,pdbs)

sm = query(db)

mean = meanquery(db)

res, meanres = GDP(db,noise1,noise2)

print("The original Sum value of the DB:",sm.item())

print("The Sum value after adding noise:",res.item())

print("The original Sum value of the DB:",mean.item())

print("The Sum value after adding noise:",meanres.item())

The original Sum value of the DB: 488.0
The Sum value after adding noise: 335.72735595703125
The original Sum value of the DB: 0.4880000054836273
The Sum value after adding noise: 616.7572631835938


In [0]:
noise1,noise2 = cal(0.0005,db,pdbs)

sm = query(db)

mean = meanquery(db)

res, meanres = GDP(db,noise1,noise2)

print("The original Sum value of the DB:",sm.item())

print("The Sum value after adding noise:",res.item())

print("The original Sum value of the DB:",mean.item())

print("The Sum value after adding noise:",meanres.item())

The original Sum value of the DB: 488.0
The Sum value after adding noise: 1650.3331298828125
The original Sum value of the DB: 0.4880000054836273
The Sum value after adding noise: 402.154541015625


# Lesson: The Formal Definition of Differential Privacy

The previous method of adding noise was called "Local Differentail Privacy" because we added noise to each datapoint individually. This is necessary for some situations wherein the data is SO sensitive that individuals do not trust noise to be added later. However, it comes at a very high cost in terms of accuracy. 

However, alternatively we can add noise AFTER data has been aggregated by a function. This kind of noise can allow for similar levels of protection with a lower affect on accuracy. However, participants must be able to trust that no-one looked at their datapoints _before_ the aggregation took place. In some situations this works out well, in others (such as an individual hand-surveying a group of people), this is less realistic.

Nevertheless, global differential privacy is incredibly important because it allows us to perform differential privacy on smaller groups of individuals with lower amounts of noise. Let's revisit our sum functions.

In [0]:
db, pdbs = create_db_and_parallels(100)

def query(db):
    return torch.sum(db.float())

def M(db):
    query(db) + noise

query(db)

So the idea here is that we want to add noise to the output of our function. We actually have two different kinds of noise we can add - Laplacian Noise or Gaussian Noise. However, before we do so at this point we need to dive into the formal definition of Differential Privacy.

![alt text](dp_formula.png "Title")

_Image From: "The Algorithmic Foundations of Differential Privacy" - Cynthia Dwork and Aaron Roth - https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf_

This definition does not _create_ differential privacy, instead it is a measure of how much privacy is afforded by a query M. Specifically, it's a comparison between running the query M on a database (x) and a parallel database (y). As you remember, parallel databases are defined to be the same as a full database (x) with one entry/person removed.

Thus, this definition says that FOR ALL parallel databases, the maximum distance between a query on database (x) and the same query on database (y) will be e^epsilon, but that occasionally this constraint won't hold with probability delta. Thus, this theorem is called "epsilon delta" differential privacy.

# Epsilon

Let's unpack the intuition of this for a moment. 

Epsilon Zero: If a query satisfied this inequality where epsilon was set to 0, then that would mean that the query for all parallel databases outputed the exact same value as the full database. As you may remember, when we calculated the "threshold" function, often the Sensitivity was 0. In that case, the epsilon also happened to be zero.

Epsilon One: If a query satisfied this inequality with epsilon 1, then the maximum distance between all queries would be 1 - or more precisely - the maximum distance between the two random distributions M(x) and M(y) is 1 (because all these queries have some amount of randomness in them, just like we observed in the last section).

# Delta

Delta is basically the probability that epsilon breaks. Namely, sometimes the epsilon is different for some queries than it is for others. For example, you may remember when we were calculating the sensitivity of threshold, most of the time sensitivity was 0 but sometimes it was 1. Thus, we could calculate this as "epsilon zero but non-zero delta" which would say that epsilon is perfect except for some probability of the time when it's arbitrarily higher. Note that this expression doesn't represent the full tradeoff between epsilon and delta.

# Lesson: How To Add Noise for Global Differential Privacy

In this lesson, we're going to learn about how to take a query and add varying amounts of noise so that it satisfies a certain degree of differential privacy. In particular, we're going to leave behind the Local Differential privacy previously discussed and instead opt to focus on Global differential privacy. 

So, to sum up, this lesson is about adding noise to the output of our query so that it satisfies a certain epsilon-delta differential privacy threshold.

There are two kinds of noise we can add - Gaussian Noise or Laplacian Noise. Generally speaking Laplacian is better, but both are still valid. Now to the hard question...

### How much noise should we add?

The amount of noise necessary to add to the output of a query is a function of four things:

- the type of noise (Gaussian/Laplacian)
- the sensitivity of the query/function
- the desired epsilon (ε)
- the desired delta (δ)

Thus, for each type of noise we're adding, we have different way of calculating how much to add as a function of sensitivity, epsilon, and delta. We're going to focus on Laplacian noise. Laplacian noise is increased/decreased according to a "scale" parameter b. We choose "b" based on the following formula.

b = sensitivity(query) / epsilon

In other words, if we set b to be this value, then we know that we will have a privacy leakage of <= epsilon. Furthermore, the nice thing about Laplace is that it guarantees this with delta == 0. There are some tunings where we can have very low epsilon where delta is non-zero, but we'll ignore them for now.

### Querying Repeatedly

- if we query the database multiple times - we can simply add the epsilons (Even if we change the amount of noise and their epsilons are not the same).

# Project: Create a Differentially Private Query

In this project, I want you to take what you learned in the previous lesson and create a query function which sums over the database and adds just the right amount of noise such that it satisfies an epsilon constraint. Write a query for both "sum" and for "mean". Ensure that you use the correct sensitivity measures for both.

In [0]:
# try this project here!

# Lesson: Differential Privacy for Deep Learning

So in the last lessons you may have been wondering - what does all of this have to do with Deep Learning? Well, these same techniques we were just studying form the core primitives for how Differential Privacy provides guarantees in the context of Deep Learning. 

Previously, we defined perfect privacy as "a query to a database returns the same value even if we remove any person from the database", and used this intuition in the description of epsilon/delta. In the context of deep learning we have a similar standard.

Training a model on a dataset should return the same model even if we remove any person from the dataset.

Thus, we've replaced "querying a database" with "training a model on a dataset". In essence, the training process is a kind of query. However, one should note that this adds two points of complexity which database queries did not have:

    1. do we always know where "people" are referenced in the dataset?
    2. neural models rarely never train to the same output model, even on identical data

The answer to (1) is to treat each training example as a single, separate person. Strictly speaking, this is often overly zealous as some training examples have no relevance to people and others may have multiple/partial (consider an image with multiple people contained within it). Thus, localizing exactly where "people" are referenced, and thus how much your model would change if people were removed, is challenging.

The answer to (2) is also an open problem - but several interesitng proposals have been made. We're going to focus on one of the most popular proposals, PATE.

## An Example Scenario: A Health Neural Network

First we're going to consider a scenario - you work for a hospital and you have a large collection of images about your patients. However, you don't know what's in them. You would like to use these images to develop a neural network which can automatically classify them, however since your images aren't labeled, they aren't sufficient to train a classifier. 

However, being a cunning strategist, you realize that you can reach out to 10 partner hospitals which DO have annotated data. It is your hope to train your new classifier on their datasets so that you can automatically label your own. While these hospitals are interested in helping, they have privacy concerns regarding information about their patients. Thus, you will use the following technique to train a classifier which protects the privacy of patients in the other hospitals.

- 1) You'll ask each of the 10 hospitals to train a model on their own datasets (All of which have the same kinds of labels)
- 2) You'll then use each of the 10 partner models to predict on your local dataset, generating 10 labels for each of your datapoints
- 3) Then, for each local data point (now with 10 labels), you will perform a DP query to generate the final true label. This query is a "max" function, where "max" is the most frequent label across the 10 labels. We will need to add laplacian noise to make this Differentially Private to a certain epsilon/delta constraint.
- 4) Finally, we will retrain a new model on our local dataset which now has labels. This will be our final "DP" model.

So, let's walk through these steps. I will assume you're already familiar with how to train/predict a deep neural network, so we'll skip steps 1 and 2 and work with example data. We'll focus instead on step 3, namely how to perform the DP query for each example using toy data.

So, let's say we have 10,000 training examples, and we've got 10 labels for each example (from our 10 "teacher models" which were trained directly on private data). Each label is chosen from a set of 10 possible labels (categories) for each image.

In [0]:
import numpy as np
import torch

In [0]:
num_teachers = 10 # we're working with 10 partner hospitals
num_examples = 10000 # the size of OUR dataset
num_labels = 10 # number of lablels for our classifier

In [0]:
preds = (np.random.rand(num_teachers, num_examples) * num_labels).astype(int).transpose(1,0) # fake predictions

In [14]:
print(f'Actua: {preds[0:,0]}')
      
a = np.bincount(preds[:,0],minlength=10)

print(f'Counts:{a}')
print(f'Max: {np.argmax(a)}')      

B = torch.rand(1) >0.5
print(B)
noisy_count = a + np.random.laplace(0,B, 1)
      
print(f'Max with noise: {noisy_count}')
print(f'Max: {np.argmax(noisy_count)}')

Actua: [8 6 9 ... 8 1 4]
Counts:[1000 1007  956 1005  977  990  983 1067 1014 1001]
Max: 7
tensor([0], dtype=torch.uint8)
Max with noise: [1000. 1007.  956. 1005.  977.  990.  983. 1067. 1014. 1001.]
Max: 7


In [0]:
new_labels = list()
for an_image in preds:

    label_counts = np.bincount(an_image, minlength=num_labels)

    epsilon = 0.1
    beta = 1 / epsilon

    for i in range(len(label_counts)):
        label_counts[i] += np.random.laplace(0, beta, 1)

    new_label = np.argmax(label_counts)
    
    new_labels.append(new_label)

In [18]:
print(f'New Labels: ',(new_labels))
print(f'Max: {np.argmax(new_labels)}')


New Labels:  [2, 5, 6, 3, 5, 2, 4, 5, 3, 9, 3, 6, 9, 9, 8, 2, 8, 9, 9, 3, 6, 1, 3, 2, 6, 3, 2, 2, 7, 2, 4, 8, 9, 8, 3, 8, 9, 6, 9, 6, 2, 4, 4, 4, 4, 5, 9, 0, 2, 9, 2, 0, 9, 8, 7, 7, 4, 1, 3, 3, 8, 4, 5, 1, 0, 8, 4, 2, 7, 9, 7, 1, 5, 5, 9, 3, 7, 5, 3, 6, 6, 2, 3, 8, 1, 2, 5, 4, 3, 1, 2, 1, 4, 1, 1, 5, 3, 7, 0, 3, 2, 9, 7, 0, 8, 0, 4, 7, 8, 7, 8, 4, 1, 1, 2, 4, 0, 4, 7, 4, 8, 7, 6, 9, 0, 0, 0, 6, 0, 3, 8, 3, 9, 7, 9, 7, 6, 0, 3, 5, 9, 7, 8, 2, 2, 2, 5, 5, 6, 9, 2, 8, 1, 0, 2, 4, 6, 9, 0, 0, 6, 1, 9, 0, 1, 6, 4, 1, 5, 0, 1, 8, 2, 2, 9, 7, 5, 4, 1, 8, 5, 1, 8, 8, 2, 3, 6, 8, 9, 0, 3, 6, 7, 9, 2, 6, 9, 5, 5, 3, 0, 4, 2, 0, 4, 0, 9, 7, 3, 3, 1, 3, 3, 1, 1, 3, 9, 0, 0, 4, 6, 8, 9, 1, 0, 6, 3, 2, 0, 1, 1, 5, 6, 0, 7, 9, 4, 5, 8, 6, 2, 7, 7, 5, 6, 7, 9, 6, 5, 4, 4, 6, 5, 8, 1, 7, 6, 9, 9, 0, 6, 6, 1, 4, 3, 3, 8, 7, 7, 5, 3, 0, 3, 7, 6, 1, 4, 5, 9, 2, 7, 3, 7, 9, 0, 4, 2, 2, 8, 7, 7, 1, 0, 7, 9, 9, 7, 5, 1, 8, 4, 7, 4, 4, 8, 8, 2, 6, 6, 4, 6, 9, 0, 5, 1, 0, 3, 6, 5, 3, 8, 5, 1, 1, 1, 4, 2, 9, 9,

# PATE Analysis

In [19]:
labels = np.array([9, 9, 3, 6, 9, 9, 9, 9, 8, 2])
counts = np.bincount(labels, minlength=10)
query_result = np.argmax(counts)
query_result

9

In [20]:
!pip install syft
from syft.frameworks.torch.differential_privacy import pate

     |████████████████████████████████| 215kB 2.8MB/s 
     |████████████████████████████████| 450kB 60.4MB/s 
     |████████████████████████████████| 256kB 60.2MB/s 
     |████████████████████████████████| 71kB 30.7MB/s 
     |████████████████████████████████| 204kB 59.8MB/s 
     |████████████████████████████████| 389kB 51.1MB/s 
     |████████████████████████████████| 1.4MB 44.8MB/s 
     |████████████████████████████████| 51kB 23.8MB/s 
     |████████████████████████████████| 276kB 48.2MB/s 
     |████████████████████████████████| 122kB 43.7MB/s 
  Stored in directory: /root/.cache/pip/wheels/ad/9a/f4/3105b5209674ac77fcca7fede95184c62a95df0196888e0e76
  Stored in directory: /root/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
Successfully built zstd pyyaml
  Found existing installation: msgpack 0.5.6
    Uninstalling msgpack-0.5.6:
      Successfully uninstalled msgpack-0.5.6
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
   

W0626 00:09:23.291826 139819085596544 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0-rc1.so'
W0626 00:09:23.306598 139819085596544 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [21]:
num_teachers, num_examples, num_labels = (100, 100, 10)
preds = (np.random.rand(num_teachers, num_examples) * num_labels).astype(int) #fake preds
indices = (np.random.rand(num_examples) * num_labels).astype(int) # true answers

preds[:,0:10] *= 0

data_dep_eps, data_ind_eps = pate.perform_analysis(teacher_preds=preds, indices=indices, noise_eps=0.1, delta=1e-5)

assert data_dep_eps < data_ind_eps



In [22]:
data_dep_eps, data_ind_eps = pate.perform_analysis(teacher_preds=preds, indices=indices, noise_eps=0.1, delta=1e-5)
print("Data Independent Epsilon:", data_ind_eps)
print("Data Dependent Epsilon:", data_dep_eps)

Data Independent Epsilon: 11.756462732485115
Data Dependent Epsilon: 1.52655213289881


In [0]:
preds[:,0:50] *= 0

In [26]:
data_dep_eps, data_ind_eps = pate.perform_analysis(teacher_preds=preds, indices=indices, noise_eps=0.1, delta=1e-5, moments=20)
print("Data Independent Epsilon:", data_ind_eps)
print("Data Dependent Epsilon:", data_dep_eps)

Data Independent Epsilon: 11.756462732485115
Data Dependent Epsilon: 0.9029013677789843


# Where to Go From Here


Read:
* Algorithmic Foundations of Differential Privacy: https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf
* Deep Learning with Differential Privacy: https://arxiv.org/pdf/1607.00133.pdf
* The Ethical Algorithm: https://www.amazon.com/Ethical-Algorithm-Science-Socially-Design/dp/0190948205



   
Topics:
* The Exponential Mechanism
* The Moment's Accountant
*  Differentially Private Stochastic Gradient Descent

# Section Project:

For the final project for this section, you're going to train a DP model using this PATE method on the MNIST dataset, provided below.

In [0]:
import torchvision.datasets as datasets
mnist_trainset = datasets.MNIST(root='./data', train=True, download=True, transform=None)

In [0]:
train_data = mnist_trainset.train_data
train_targets = mnist_trainset.train_labels

In [0]:
test_data = mnist_trainset.test_data
test_targets = mnist_trainset.test_labels