<a href="https://colab.research.google.com/github/saisampathkumar/AI-Cybersecurity/blob/master/ICP7/L4_Federated_Learning_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section: Federated Learning

# Lesson: Introducing Federated Learning

Federated Learning is a technique for training Deep Learning models on data to which you do not have access. Basically:

Federated Learning: Instead of bringing all the data to one machine and training a model, we bring the model to the data, train it locally, and merely upload "model updates" to a central server.

Use Cases:

    - app company (Texting prediction app)
    - predictive maintenance (automobiles / industrial engines)
    - wearable medical devices
    - ad blockers / autotomplete in browsers (Firefox/Brave)
    
Challenge Description: data is distributed amongst sources but we cannot aggregated it because of:

    - privacy concerns: legal, user discomfort, competitive dynamics
    - engineering: the bandwidth/storage requirements of aggregating the larger dataset

# Lesson: Introducing / Installing PySyft

In order to perform Federated Learning, we need to be able to use Deep Learning techniques on remote machines. This will require a new set of tools. Specifically, we will use an extensin of PyTorch called PySyft.

### Install PySyft

The easiest way to install the required libraries is with [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/overview.html). Create a new environment, then install the dependencies in that environment. In your terminal:

```bash
conda create -n pysyft python=3
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
conda install jupyter notebook
pip install syft
pip install numpy
```

If you have any errors relating to zstd - run the following (if everything above installed fine then skip this step):

```
pip install --upgrade --force-reinstall zstd
```

and then retry installing syft (pip install syft).

If you are using Windows, I suggest installing [Anaconda and using the Anaconda Prompt](https://docs.anaconda.com/anaconda/user-guide/getting-started/) to work from the command line. 

With this environment activated and in the repo directory, launch Jupyter Notebook:

```bash
jupyter notebook
```

and re-open this notebook on the new Jupyter server.



In [126]:
!pip install syft
!pip install numpy

In [0]:
import torch as th

In [128]:
x = th.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [0]:
y = x + x

In [130]:
print(y)

tensor([ 2,  4,  6,  8, 10])


In [0]:
import syft as sy

In [132]:
hook = sy.TorchHook(th)  # this line of code create an instance of th with its backend APIs modified with Syft functions

W0703 00:50:23.146985 140711991842688 hook.py:98] Torch was already hooked... skipping hooking process


In [133]:
th.tensor([1,2,3,4,5]) # notice that Torch functionalities still behave the same

tensor([1, 2, 3, 4, 5])

# Lesson: Basic Remote Execution in PySyft

## PySyft => Remote PyTorch

The essence of Federated Learning is the ability to train models in parallel on a wide number of machines. Thus, we need the ability to tell remote machines to execute the operations required for Deep Learning.

Thus, instead of using Torch tensors - we're now going to work with **pointers** to tensors. Let me show you what I mean. First, let's create a "pretend" machine owned by a "pretend" person - we'll call him Bob.

In [0]:
bob = sy.VirtualWorker(hook, id="bob") # creates a virtual worker (a simulaion to interface to Bob machines)

In [135]:
bob._objects

{1924803445: tensor([[1., 1.],
         [0., 1.]], requires_grad=True), 12412187168: Parameter containing:
 tensor([-0.2561], requires_grad=True), 18263113491: Parameter containing:
 tensor([0.1935], requires_grad=True), 29366228773: Parameter containing:
 tensor([[ 0.3352, -0.5843]], requires_grad=True), 47203834942: Parameter containing:
 tensor([0.1935], requires_grad=True), 53871493201: tensor([[-0.5706],
         [-1.0494]], grad_fn=<AddmmBackward>), 54710610522: tensor([[1.],
         [1.]], requires_grad=True), 57455923546: Parameter containing:
 tensor([[ 0.3282, -0.0256]], requires_grad=True), 58120181075: Parameter containing:
 tensor([[ 0.5723, -0.3707]], requires_grad=True), 64100681601: tensor([[1.],
         [1.]], requires_grad=True), 67237665200: Parameter containing:
 tensor([[ 0.4420, -0.1304]], requires_grad=True), 70437269389: Parameter containing:
 tensor([[0.1314, 0.0337]], requires_grad=True), 72548508742: tensor([1, 2, 3, 4, 5]), 74804331759: Parameter containin

In [0]:
x = th.tensor([1,2,3,4,5])

In [0]:
x_ptr =  x.send(bob) # send this data to bob

In [138]:
bob._objects

{1924803445: tensor([[1., 1.],
         [0., 1.]], requires_grad=True), 12412187168: Parameter containing:
 tensor([-0.2561], requires_grad=True), 18263113491: Parameter containing:
 tensor([0.1935], requires_grad=True), 29366228773: Parameter containing:
 tensor([[ 0.3352, -0.5843]], requires_grad=True), 47203834942: Parameter containing:
 tensor([0.1935], requires_grad=True), 53871493201: tensor([[-0.5706],
         [-1.0494]], grad_fn=<AddmmBackward>), 54710610522: tensor([[1.],
         [1.]], requires_grad=True), 57455923546: Parameter containing:
 tensor([[ 0.3282, -0.0256]], requires_grad=True), 58120181075: Parameter containing:
 tensor([[ 0.5723, -0.3707]], requires_grad=True), 64100681601: tensor([[1.],
         [1.]], requires_grad=True), 67237665200: Parameter containing:
 tensor([[ 0.4420, -0.1304]], requires_grad=True), 70437269389: Parameter containing:
 tensor([[0.1314, 0.0337]], requires_grad=True), 72548508742: tensor([1, 2, 3, 4, 5]), 74549600727: tensor([1, 2, 3, 4,

In [139]:
x_ptr

(Wrapper)>[PointerTensor | me:89507320194 -> bob:74549600727]

In [140]:
x.location

AttributeError: ignored

In [0]:
x.id_at_location

In [0]:
x.id

In [0]:
x.owner

In [0]:
hook.local_worker

In [0]:
x = x.get()
x

In [0]:
bob._objects

# Project: Experience with Remote Tensors

In this project, I want you to .send() and .get() a tensor to TWO workers by calling .send(bob,alice). This will first require the creation of another VirtualWorker called alice.

In [0]:
# create a second Virtual worker and call it Alice


In [0]:
# 1 - create some data (a tensor)
# 2- send the data to bob and alice


In [0]:
# notice what does the send fucntion on two workers return; a multi-pointer
x_ptr

In [0]:
# what does .child on the pointer object return?
# what does .child.child on the pointer object return? 

In [0]:
# try the .get() on the pointer


In [0]:
# try the .get(sum_results=True) on your pointer


# Lesson: Introducing Remote Arithmetic

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(bob)

In [0]:
x # a pointer to a remote tensor located at bob

In [0]:
y # a pointer to another remote tensor located at bob

In [0]:
z = x + y # treat those tensors (i.e., x and y) as local tensors, but they are actually executed remotely
z

In [0]:
z = z.get()
z

In [0]:
z = th.add(x,y) # we can also use Torch operation on these tensors to be executed remotely
z

In [0]:
z = z.get() # yup! same results!
z

In [0]:
x = th.tensor([1.,2,3,4,5], requires_grad=True).send(bob)
y = th.tensor([1.,1,1,1,1], requires_grad=True).send(bob)

In [0]:
z = (x + y).sum()
z = z.get()
z

In [0]:
z.backward() 

In [0]:
x = x.get()

In [0]:
x

In [0]:
x.grad

# Project: Learn a Simple Linear Model

In this project, I'd like for you to create a simple linear model which will solve for the following dataset below. You should use only Variables and .backward() to do so (no optimizers or nn.Modules). 

Furthermore, you must do so with both the data and the model being located on Bob's machine.

In [0]:
import torch as th
import syft as sy

hook = sy.TorchHook(th)  
bob = sy.VirtualWorker(hook, id="bob")

bob

In [0]:
# create some toy data for our model
input_data = th.tensor([[1.,1],[0.5,1],[1,0],[0,0]], requires_grad=True).send(bob)
output_data = th.tensor([[1.],[1],[0],[0]], requires_grad=True).send(bob)

In [0]:
# send the data to bob

In [0]:
# create some linear weights and send them to bob
weights = th.tensor([[0.01],[0.01]], requires_grad = True).send(bob)

In [0]:
# create a linear model and train it on Bob's machine
# remember how to create a linear model? No? :( 
# Here's the main steps:
#    1- find a prediction
#    2- calcualte the loss (a mean square loss)
#    3- backpropogate using the backword() function
#    4- DO NOT forget to clear your gradients after updating the weights
#    weights.data.sub_(weights.grad * lr)

prediction = input_data.mm(weights)
prediction

In [0]:
lr = 0.1

prediction = input_data.mm(weights)
prediction

for i in range(10):
  prediction = input_data.mm(weights)
  loss = ((prediction - output_data)**2).mean()
  loss.backward()
  weights.data.sub_(weights.grad * lr)
  weights.grad *= 0

  print(loss.get().data)

# Lesson: Garbage Collection and Common Errors


In [0]:
bob = bob.clear_objects() # clear the contents of a remote object

In [0]:
bob._objects

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects

In [0]:
del x  # delete the pointer to the remote object

In [0]:
bob._objects

In [0]:
x.child.garbage_collect_data  # True by default

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects

In [0]:
x = "asdf"

In [0]:
bob._objects

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
x

In [0]:
bob._objects

In [0]:
x = "asdf"

In [0]:
bob._objects  # some error from Jupyter is casuing this to appear!

In [0]:
del x

In [0]:
bob._objects

In [0]:
bob = bob.clear_objects() # erase force 
bob._objects

In [0]:
for i in range(1000):
    x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects # notice that there is only a single tensor in bob

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1])

In [0]:
z = x + y

In [0]:
alice = sy.VirtualWorker(hook, id="alice")
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(alice)

In [0]:
z = x + y

# Lesson: Toy Federated Learning

Let's start by training a toy model the centralized way. This is about a simple as models get. We first need:

- a toy dataset
- a model
- some basic training logic for training a model to fit the data.

In [0]:
from torch import nn, optim

In [0]:
# A Toy Dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = th.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# A Toy Model
model = nn.Linear(2,1)

In [0]:
opt = optim.SGD(params=model.parameters(), lr=0.1)

In [0]:
def train(iterations=10):
    for iter in range(iterations):
        opt.zero_grad()

        pred = model(data)

        loss = ((pred - target)**2).sum()

        loss.backward()

        opt.step()

        print(loss.data)
        
train()

In [0]:
# nothing was federated up to this point!

import torch as th
import syft as sy

hook = sy.TorchHook(th)  
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")



In [0]:
# create local datasets at Bob and Alice
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

data_alice = data[2:4].send(alice)
target_alice = target[2:4].send(alice)

In [0]:
datasets = [(data_bob, target_bob), (data_alice, target_alice)]
datasets

In [0]:
def train(iterations=1):

    model = nn.Linear(2,1)
    opt = optim.SGD(params=model.parameters(), lr=0.1)
    
    for iter in range(iterations):

        for _data, _target in datasets:

            # send model to the data
            model = model.send(_data.location)

            # do training on the remote machine
            opt.zero_grad()
            pred = model(_data)
            loss = ((pred - _target)**2).sum()
            loss.backward()
            opt.step()

            # get smarter model back
            model = model.get()

            print(loss.get())

In [0]:
train()

# Lesson: Advanced Remote Execution Tools

In the last section we trained a toy model using Federated Learning. We did this by calling .send() and .get() on our model, sending it to the location of training data, updating it, and then bringing it back. However, at the end of the example we realized that we needed to go a bit further to protect people privacy. Namely, we want to average the gradients BEFORE calling .get(). That way, we won't ever see anyone's exact gradient (thus better protecting their privacy!!!)

But, in order to do this, we need a few more pieces:

- use a pointer to send a Tensor directly to another worker

And in addition, while we're here, we're going to learn about a few more advanced tensor operations as well which will help us both with this example and a few in the future!

In [0]:
bob.clear_objects()
alice.clear_objects()

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
x = x.send(alice)

In [0]:
bob._objects

In [0]:
alice._objects

In [0]:
y = x + x

In [0]:
y

In [0]:
bob._objects

In [0]:
alice._objects

In [0]:
jon = sy.VirtualWorker(hook, id="jon")

In [0]:
bob.clear_objects()
alice.clear_objects()



In [0]:
x = th.tensor([1,2,3,4,5]).send(bob).send(alice)
y = th.tensor([1,2,3,4,5]).send(bob).send(jon)

In [0]:
z = x + y

In [0]:
x = x.get() # to get the data back
x

In [0]:
bob._objects

In [0]:
alice._objects

In [0]:
x = x.get()
x

In [0]:
bob._objects

# Lesson: Pointer Chain Operations

In [31]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [33]:
bob._objects

{}

In [34]:
alice._objects

{}

In [35]:
x.move(alice)

KeyError: ignored

In [36]:
x

(Wrapper)>[PointerTensor | me:98033353878 -> bob:48423199195]

In [37]:
bob._objects

{}

In [38]:
alice._objects

{}

In [39]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob).send(alice)

In [41]:
bob._objects

{}

In [42]:
alice._objects

{}

In [43]:
x

(Wrapper)>[PointerTensor | me:28544930800 -> alice:9864969118]

In [44]:
x.remote_get() # inplace operation

KeyError: ignored

In [0]:
bob._objects

In [0]:
alice._objects

In [0]:
x.move(bob)

In [0]:
x

In [0]:
bob._objects

In [0]:
alice._objects

**Exercise 1:**

- Create a toy dataset
- Create a toy linear model
- Train the dataset using Federated Learning, but do not share the gradiant with the main server, instead use the move function to send the gradients to one of the participating workers, aggregate the model, then send the final model to the main server (i.e., local worker).



---


**Exercise 2:**

While exercise 1 illustrates a good example of preseving privacy in FL, we still had to expose the gradients to one of the participating workers. To avoid this limitation, you need to send the gradiants to a TRUSTED thirdparty (trusted aggregator) who will aggregate the models and then send the final model to the server (local worker). In this way, we assure that none of the participating workers can access the aggregated model!

1. create a dataset for each worker (create two)
2. create a model for each worker and train it remotely on each worker
3. send those two models using the *move()* function to a third worker
4. the third workers aggregates the two models (find their mean)
5. send the aggregated model to the main server (local worker) using the *get()* function



---

To set the weights: `model.weight.set_()`



In [0]:
# Exercise 1
import syft as sy
import torch as th
from torch import nn, optim

In [50]:
hook = sy.TorchHook(th)

W0703 01:06:13.126478 139912716588928 hook.py:98] Torch was already hooked... skipping hooking process


In [0]:
# create workers
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
secureWorker = sy.VirtualWorker(hook, id="secureWorker")

In [52]:
# Make each worker aware of the other workers
bob.add_workers([alice,secureWorker])
alice.add_workers([bob,secureWorker])
secureWorker.add_workers([bob, alice])

W0703 01:06:16.061093 139912716588928 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:06:16.065978 139912716588928 base.py:628] Worker secureWorker already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:06:16.069695 139912716588928 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:06:16.072933 139912716588928 base.py:628] Worker secureWorker already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:06:16.075088 139912716588928 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0703 01:06:16.078889 139912716588928 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior


<VirtualWorker id:secureWorker #objects:0>

In [53]:
print(bob._objects)
print(alice._objects)
print(secureWorker._objects)

{32169205075: tensor([[1., 1.],
        [0., 1.]], requires_grad=True), 38408452052: tensor([[1.],
        [1.]], requires_grad=True), 61614846422: tensor([[1., 1.],
        [0., 1.]], requires_grad=True), 88379336569: tensor([[1.],
        [1.]], requires_grad=True), 67878386593: tensor([[0.9981],
        [1.0025]], grad_fn=<AddmmBackward>), 51522352712: tensor([1, 2, 3, 4, 5])}
{8913700183: tensor([[1., 0.],
        [0., 0.]], requires_grad=True), 2802236590: tensor([[0.],
        [0.]], requires_grad=True), 92238466377: tensor([[1., 0.],
        [0., 0.]], requires_grad=True), 6287884743: tensor([[0.],
        [0.]], requires_grad=True), 74954078868: tensor([[-0.0246],
        [ 0.0398]], grad_fn=<AddmmBackward>), 9864969118: (Wrapper)>[PointerTensor | alice:9864969118 -> bob:51522352712]}
{}


In [0]:
# A Toy Dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = th.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# create local datasets at Bob and Alice
Bdata = data[0:2].send(bob)

Btarget = target[0:2].send(bob)

Adata = data[2:].send(alice)

Atarget = target[2:].send(alice)


In [0]:
# create a linear model at local worker
model = nn.Linear(2,1)

In [0]:
# Send copies of the linear model to alice and bob
Bmodel = model.copy().send(bob)
Amodel = model.copy().send(alice)

In [0]:
Bopt = optim.SGD(params=Bmodel.parameters(), lr=0.1)
Aopt = optim.SGD(params=Amodel.parameters(), lr=0.1)

In [59]:
# train the models at alice and bob
# move the models to the third worker
# aggreegate the models
# send the model back to the local worker            

for i in range(10):
  # do training on the remote machine
  Bopt.zero_grad()
  Bpred = Bmodel(Bdata)
  Bloss = ((Bpred - Btarget)**2).sum()
  Bloss.backward()
  Bopt.step()
  print(Bloss.get().data)      



tensor(5.5423)
tensor(0.0602)
tensor(0.0151)
tensor(0.0123)
tensor(0.0102)
tensor(0.0085)
tensor(0.0071)
tensor(0.0059)
tensor(0.0049)
tensor(0.0041)


In [60]:
for i in range(10):
  # do training on the remote machine
  Aopt.zero_grad()
  Apred = Amodel(Adata)
  Aloss = ((Apred - Atarget)**2).sum()
  Aloss.backward()
  Aopt.step()
  print(Aloss.get().data)
    

        

tensor(1.5643)
tensor(0.3693)
tensor(0.0959)
tensor(0.0321)
tensor(0.0161)
tensor(0.0112)
tensor(0.0090)
tensor(0.0075)
tensor(0.0064)
tensor(0.0054)


In [0]:
Bmodel.move(secureWorker)
Amodel.move(secureWorker)

In [63]:
print(secureWorker._objects)

{79544961765: Parameter containing:
tensor([[-0.0819,  0.8820]], requires_grad=True), 31882522932: Parameter containing:
tensor([0.1640], requires_grad=True), 29468944719: Parameter containing:
tensor([[-0.0940,  0.1936]], requires_grad=True), 87913710499: Parameter containing:
tensor([0.0576], requires_grad=True)}


In [69]:
print(((Amodel.weight.data + Bmodel.weight.data) / 2).get())

tensor([[-0.0879,  0.5378]])


In [0]:
x = th.tensor((((Amodel.weight.data + Bmodel.weight.data) / 2).get())).send(model)
x

In [77]:
import torch as th
import syft as sy

hook = sy.TorchHook(th)  
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
secureWorker = sy.VirtualWorker(hook, id="secureWorker")

print(bob)
print(alice)
print(secureWorker)

W0703 01:33:41.517493 139912716588928 hook.py:98] Torch was already hooked... skipping hooking process


<VirtualWorker id:bob #objects:6>
<VirtualWorker id:alice #objects:6>
<VirtualWorker id:secureWorker #objects:5>


In [0]:
data = th.tensor([[1.,1],[0.5,1],[1,0],[0,0]], requires_grad=True)
target = th.tensor([[1.],[1],[0],[0]], requires_grad=True)

In [0]:
Bweights = th.tensor([[0.01],[0.01]], requires_grad = True).send(bob)
Aweights = th.tensor([[0.02],[0.02]], requires_grad = True).send(alice)

In [0]:
Bdata = data[0:2].send(bob)

Btarget = target[0:2].send(bob)

Adata = data[2:].send(alice)

Atarget = target[2:].send(alice)

In [0]:


Bprediction = Bdata.mm(Bweights)
Aprediction = Adata.mm(Aweights)




In [85]:
lr = 0.1

for i in range(10):
  Bprediction = Bdata.mm(Bweights)
  Bloss = ((Bprediction - Btarget)**2).mean()
  Bloss.backward()
  Bweights.data.sub_(Bweights.grad * lr)
  Bweights.grad *= 0

  print(Bloss.get().data)

tensor(0.9653)
tensor(0.0826)
tensor(0.0458)
tensor(0.0285)
tensor(0.0204)
tensor(0.0165)
tensor(0.0145)
tensor(0.0135)
tensor(0.0129)
tensor(0.0126)


In [87]:
lr = 0.1

for i in range(10):
  Aprediction = Adata.mm(Aweights)
  Aloss = ((Aprediction - Atarget)**2).mean()
  Aloss.backward()
  Aweights.data.sub_(Aweights.grad * lr)
  Aweights.grad *= 0

  print(Aloss.get().data)

tensor(0.0002)
tensor(0.0001)
tensor(0.0001)
tensor(8.6093e-05)
tensor(6.9736e-05)
tensor(5.6486e-05)
tensor(4.5754e-05)
tensor(3.7060e-05)
tensor(3.0019e-05)
tensor(2.4315e-05)
